### ISSUE TITLE
Missing \begin{document}

### ISSUE THREAD

**Issue by maik123456789** [kbroman/GSATemplate#1]
Hello!
Sorry, I am new to Latex. I was modifying a latex document and I got problems with this template (I thought it was outdated), so I came here and try to run the example and I have the same problems...

I am running the GSA-G3-journal-template.tex example.

I attach a screenshot of the console. Could you help me please?

![imagen](https://user-images.githubusercontent.com/54273123/115671821-327f2480-a34b-11eb-925a-cb35a4f67f69.png)

**Comment by kbroman** [comment]
No.

Maybe try <https://tex.stackexchange.com/>
