### ISSUE TITLE
Templates are outdated

### ISSUE THREAD

**Issue by tomh-overleaf** [kbroman/GSATemplate#2]
These are not the latest versions of the templates. Namely they cause an error due to an incompatibility of `\makeatother` within the `.cls` file and new versions of LaTeX2e.

They should be updated to match the official versions at:
- https://www.overleaf.com/latex/templates/template-for-preparing-your-submission-to-genetics-using-overleaf/stmpddtqcxtx
- https://www.overleaf.com/latex/templates/template-for-preparing-your-submission-to-g3-genes-genomes-genetics-using-overleaf/vffkrpmjrcgf

See comments at https://tex.stackexchange.com/q/594115/11002 for details.

**Comment by kbroman** [comment]
done, thanks
